### ISSUE TITLE
Allow for variable TimeOut Periods

### ISSUE THREAD

**Issue by tgb417** [micahwalter/tessitura-tools#5]
For Website use, 15 seconds seems like a reasonable time out period.  However, for data science data transfer it might be useful to allow longer time out periods.  Could we / should we move this to an optional variable with a default built into the code if not otherwise specified?

Thoughts?

**Comment by micahwalter** [comment]
ok this is done in version 0.0.7 which is now on PyPi.. to use, just add an optional parameter to your requests like `timeout=20` the default is 15

**Comment by tgb417** [comment]
Cool Thanks Next time In my code I'll transfer back to the public version and do some testing.
