### ISSUE TITLE
We need to support DELETE REST API calls

### ISSUE THREAD

**Issue by tgb417** [micahwalter/tessitura-tools#6]
The subject says it all.

We need to support a DELETE REST API call

**Comment by micahwalter** [comment]
potential fix here https://github.com/micahwalterstudio/tessitura-tools/pull/7

**Comment by tgb417** [comment]
@micahwalter 
I've done a confirmation test with a real API and the pypi (pip install tessitura) library.  I've been able to make a delete work.  

So thank you for the push of the 0.0.8 version of our library.

One of the interesting things about this approach is that the returned json produces no error and an empty result {}.  

Do you think that this is confusing?
