### ISSUE TITLE
Different number of columns for timeouts and Tessitura Submitted errors.

### ISSUE THREAD

**Issue by tgb417** [micahwalter/tessitura-tools#8]
Micah,

Hope you are well.  

As I've been using the library.  I've been running into a little bit of a challenge when looking at errors.
If one has a time out we get 2 "columns" of data returned by the Tessitura Library.  If we get a tessitura derived error we end up with 3 "columns" of data.  I'm wondering if for consistency e should be called info rather than e.

Thoughts?

Here is the section of the code I'm looking at

    except Exception as e:
        
        timeout = {
            "error": 500,
            "message": "Time Out Error connecting to Tessitura",
            "e": e
        }

        return timeout
        
    if r.status_code != 200:
        j = {
            "error": r.status_code,
            "message": r.reason,
        }

        if r.text:
            j["info"] = r.json()

**Comment by micahwalter** [comment]
Yes I think you are right. That whole block of code is also pretty
confusing. I’ll have a look at cleaning it up soon.

M

**Comment by tgb417** [comment]
I've got a test copy here at LSC where I've made the name of the column "e" "info" to match the other the other error messages.

**Comment by micahwalter** [comment]
ok this is fixed in version 0.0.9. Please let me know what you think.

**Comment by tgb417** [comment]
The first test seems fine.  More tests will be needed over time.
